//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegEntities : DbContext
    {
        public MegEntities()
            : base("name=MegEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Applicant> Applicants { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventReportPic> EventReportPics { get; set; }
        public DbSet<MailingList> MailingLists { get; set; }
        public DbSet<MUser> MUsers { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
    }
}
