//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventReportPic
    {
        public System.Guid ID { get; set; }
        public string OriginalFileNmae { get; set; }
        public string ImageExtension { get; set; }
        public Nullable<System.Guid> EventID { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
