//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Presenter { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<double> StartTime { get; set; }
        public Nullable<double> EndTime { get; set; }
        public string Venue1 { get; set; }
        public string Venue2 { get; set; }
        public string Venue3 { get; set; }
        public string Venue4 { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> SeatsTaken { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<bool> HasImage { get; set; }
        public string ImageExtension { get; set; }
        public Nullable<System.DateTime> ReminderSendDate { get; set; }
        public Nullable<bool> ReminderSent { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TitleType { get; set; }
    
        public virtual MUser MUser { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
