//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> NoSeats { get; set; }
        public Nullable<bool> MemberMeg { get; set; }
        public Nullable<bool> MemberIpenz { get; set; }
        public Nullable<bool> MemberImeche { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<System.Guid> EventID { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
