//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public System.Guid ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PersonalAddress { get; set; }
        public string BusinessAddress { get; set; }
        public string PreferredAddress { get; set; }
        public string PersonalPhone { get; set; }
        public string BusinessPhone { get; set; }
        public string PreferredPhone { get; set; }
        public string PersonalEmail { get; set; }
        public string BusinessEmail { get; set; }
        public string PreferredEmail { get; set; }
        public string AcademicQualifications { get; set; }
        public string WorkExperience { get; set; }
        public string Employeer { get; set; }
        public string LearnedSocieties { get; set; }
    }
}
