//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUser
    {
        public MUser()
        {
            this.Events = new HashSet<Event>();
        }
    
        public System.Guid ID { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> EmailCode { get; set; }
        public Nullable<bool> EmailVerified { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public Nullable<System.DateTime> LastLockoutDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public Nullable<int> FailedPasswordAnswerAttemptCount { get; set; }
        public Nullable<bool> IsBusinessRelated { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
